[project]
name = "minor-search"
version = "0.1.0"
description = "Focused Tavily + Gemini search pipeline for Miner"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tavily-python>=0.7.12",
    "deep-translator>=1.11.4",
    "google-generativeai>=0.7.2",
    "minio>=7.2.7",
]
